# version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zoo-data:/var/lib/zookeeper/data
      - zoo-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 3040:3040
    environment:
      ADV_HOST: 127.0.0.1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      WEB_PORT: 3040
      BROKER_PORT: 9092
    volumes:
      - kafka-data:/var/lib/kafka/data
  
  db:
    image: postgres:16
    container_name: pg-db
    environment:
      POSTGRES_USER: wiki
      POSTGRES_PASSWORD: wiki
      POSTGRES_DB: wikistream
    ports:
      - 5432:5432
    volumes:
      - pg-db:/var/lib/postgresql/data
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql

volumes:
  zoo-data:
  zoo-log:
  kafka-data:
  pg-db:
