SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGHT as PRODUCT_NAME_LENGTH,
    PRODUCT_DESCRIPTION_LENGHT as PRODUCT_DESCRIPTION_LENGTH,
    PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_WIDTH_CM,
    PRODUCT_HEIGHT_CM
FROM {{ source('olist_raw', 'raw_products') }}